name: Bandit Security Scan
on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install Bandit
        run: pip install bandit
      
      - name: Run Bandit Scan
        run: bandit -r .
